timeout 30;
server
{
	listen localhost 8080;
	serverName server1;
	clientMaxBodySize 1048576;
	errorPage 404 ../404.html;
	errorPage 400 ../400.html;
	errorPage 403 ../403.html;
	errorPage 405 ../405.html;
	errorPage 413 ../413.html;
	errorPage 500 ../500.html;
	location /upload
	{
		clientMaxBodySize 10485760;
		upload /uploads;
		allowedMethods POST;
	}
	location /obsoleteUrl
	{
		redirect 301 /;
	}
	location /cgi
	{
		root ..;
		cgi .py /usr/local/bin/python3;
		cgi .php ../../bin/php-cgi;
		allowedMethods GET POST;
	}
	location /
	{
		root ..;
		index welcome.html;
		autoIndex on;
		allowedMethods GET POST;
	}
}
server
{
	listen localhost 8080;
	serverName server2;
	clientMaxBodySize 1048576;
	errorPage 404 ../404.html;
	errorPage 400 ../400.html;
	errorPage 403 ../403.html;
	errorPage 405 ../405.html;
	errorPage 413 ../413.html;
	errorPage 500 ../500.html;
	location /upload
	{
		clientMaxBodySize 10485760;
		upload /uploads;
		allowedMethods POST;
	}
	location /obsoleteUrl
	{
		redirect 301 /;
	}
	location /
	{
		root ..;
		index welcome.html;
		autoIndex on;
		allowedMethods GET POST;
	}
}
